name = "SMLP2020"
authors = ["Phillip Alday", "Douglas Bates", "Reinhold Kliegl"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JellyMe4 = "19ac8677-9a15-4623-9afd-84acc6165ce7"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
julia = "1.5.1"
